accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.detail, name='detail'),
    path('<int:user_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/',include('reviews.urls')),
    path('accounts/', include('accounts.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:review_pk>/comment/', views.comment_create,name='comment_create'),
    path('<int:review_pk>/comment/<int:comment_pk>/delete/', views.comment_delete,name='comment_delete'),
]

reviews/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/', blank=True)
    thumbnail = ProcessedImageField(
        upload_to = 'img',
        processors = [ResizeToFill(200,300)],
        format = 'JPEG',
        options = {'quality':60},
        blank = True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    labels = { 
            'title':'제목',
            'content':'내용',
            'updated_at':'업데이트시간',
            'image':'이미지',
            'thumbnail':'썸네일'}

class Comment(models.Model):
    content = models.CharField(max_length=80)
    review = models.ForeignKey(
        Review,
        on_delete = models.CASCADE
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

reviews/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    
    class Meta: 
        model = Review
        fields = ['title','content','image','thumbnail']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ["content",]

reviews/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse
from reviews.models import Review, Comment
from reviews.forms import ReviewForm, CommentForm

# Create your views here.


def index(request):
    reviews = Review.objects.all()
    context = {"reviews": reviews}
    return render(request, "reviews/index.html", context)


def create(request):
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect("reviews:index")
    else:
        form = ReviewForm()

    context = {
        "form": form,
    }
    return render(request, "reviews/create.html", context)


def detail(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = review.comment_set.all()
    context = {
        "review": review,
        "comment_form": comment_form,
        "comments": comments,
    }
    return render(request, "reviews/detail.html", context)


def delete(request, pk):
    review = Review.objects.get(pk=pk)
    review.delete()
    return redirect("reviews:index")


def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            form.save()
            return redirect("reviews:detail", review.pk)
    else:
        form = ReviewForm(instance=review)
    context = {"form": form, "review": review}
    return render(request, "reviews/create.html", context)


def like(request, pk):
    review = Review.objects.get(pk=pk)

    if review.like_users.filter(pk=request.user.pk).exists():
        review.like_users.remove(request.user)
        is_liked = False
    else:
        review.like_users.add(request.user)
        is_liked = True

    data = {"isLiked": is_liked, "likeCount": review.like_users.count()}

    return JsonResponse(data)


def comment_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)

    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.review = review
        comment.save()
    data = {

        'username':comment.user.username,
        'content':comment.content,
        'commentCount': review.comment_set.count(),
    }
    return JsonResponse(data)


def comment_delete(request, review_pk, comment_pk):
    review = Review.objects.get(pk=review_pk)
    comment = Comment.objects.get(pk=comment_pk)
    is_deleted = False
    if request.user == comment.user:
        is_deleted = True
        comment.delete()


    data = {
        'is_deleted':is_deleted,
        'commentCount': review.comment_set.count(),
    }

    return JsonResponse(data)

reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

  {% if request.resolver_match.url_name == 'create' %}
    <h1>Create</h1>
    {%else%}
    <h1>Update</h1>
  {% endif %}
  <form action="" method='POST' enctype="multipart/form-data">

    {% csrf_token %}
    {% bootstrap_form form %}
    <input class='btn btn-success' type="submit" value='Submit'>

  </form>

{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center px-3 mb-2">
    <h1>{{ review.title }}</h1>

    <div class="d-flex">
      {% if request.user == review.user %}
        <a href="{% url 'reviews:update' review.pk %}" class="btn btn-primary me-2">수정</a>
        <a href="{% url 'reviews:delete' review.pk %}" class="btn btn-danger">삭제</a>
      {% endif %}
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <a href="{% url 'accounts:detail' review.user.pk %}" class="text-muted text-decoration-none px-3">{{ review.user }}</a>
    <p class="text-muted px-3 m-0">마지막 수정 시간:
      {{ review.updated_at|date:'Y-m-d, H:m' }}</p>
  </div>
  <hr>

  <div style="min-height: 300px" class="px-3">
    {% if review.image %}
      <div class="text-center mb-4" style="height: 30rem">
        <img src="{{ review.image.url }}" alt="{{ review.image }}" class="h-100">
      </div>
    {% endif %}

    <p class="text-break" style="white-space: pre-wrap;">{{ review.content }}</p>
  </div>
  <hr>

  {% if request.user in review.like_users.all %}
    <i id="btn-like" data-review-id="{{ review.pk }}" class="bi bi-heart-fill " style=" color: red;"></i>

  {%else%}

    <i id="btn-like" data-review-id="{{ review.pk }}" class="bi bi-heart " style=" color: red;"></i>
  {% endif %}
  <span id="likeCount">{{ review.like_users.count }}</span>
  
  <div class="px-3 my-4">
    <form id="comment-form" data-review-id="{{ review.pk }}">
      <div class="row align-items-center">
        {% csrf_token %}
        <div class="col-1">댓글
          <span class="text-primary" id="comment-count">{{ comments|length }}</span>
        </div>

        <div class="col-11 d-flex">
          {{ comment_form.content|add_class:'form-control' }}
          {% if request.user.is_authenticated %}
            <input type="submit" value="작성" class="btn btn-primary ms-3">
          {% else %}
            <input type="submit" value="작성" class="btn btn-primary disabled ms-3">
          {% endif %}
        </div>
      </div>
    </form>
  </div>

  <div >
    <div id='comments' class="px-3">
      {% for comment in comments %}
        <div id="comment-{{ comment.pk }}">
          <a href="{% url 'accounts:detail' comment.user.pk %}" class="text-muted m-0 text-decoration-none">
            {{ comment.user }}
          </a>

          <div class="d-flex align-items-center">
            <p class="m-0 me-auto">{{ comment.content }}</p>
            {% if comment.user == request.user %}
              <form data-review-id="{{ review.pk }}" data-comment-id="{{ comment.pk }}" id="comment-delete" class="comment-delete-forms m-0">
                {% csrf_token %}
                <input type="submit" value="삭제" class="btn btn-danger">
              </form>
            {% endif %}
          </div>
          <hr>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    const btnLike = document.querySelector('#btn-like')
    btnLike.addEventListener('click', event => {
      axios({
        method: 'get', 
        url: `/reviews/${event.target.dataset.reviewId}/like/`
      })
      .then(response => {
        if (response.data.isLiked === true) {
          event.target.classList.add('bi-heart-fill')
          event.target.classList.remove('bi-heart')
        } else {
          event.target.classList.add('bi-heart')
          event.target.classList.remove('bi-heart-fill')
        }
        const likeCount = document.querySelector('#likeCount')
        likeCount.innerText = response.data.likeCount
      })
    })

    // 댓글
    const commentform = document.querySelector('#comment-form')
    const csrf_token = document.querySelector('[name=csrfmiddlewaretoken]').value
    commentform.addEventListener('submit', event => {
        event.preventDefault()

        const reviewId = event.target.dataset.reviewId
        axios({
          method: 'POST',
          url: `/reviews/${reviewId}/comment/`,
          headers: {'X-CSRFToken': csrf_token},
          data: new FormData(commentform)
        })
        .then(response => {
          const comments = document.querySelector('#comments')
          const commentCount = document.querySelector('#comment-count')
          
          commentCount.innerText = response.data.commentCount
          comments.insertAdjacentHTML('beforeend',
            `
            <div id="comment-22">
              <a href="/accounts/1/" class="text-muted m-0 text-decoration-none">
                ${response.data.username}
              </a>
    
              <div class="d-flex align-items-center">
                <p class="m-0 me-auto">${response.data.content}</p>
                
                  <form data-review-id="1" data-comment-id="22" id="comment-delete" class="comment-delete-forms m-0">
                    <input type="hidden" name="csrfmiddlewaretoken" value="mgXFaQX5Vd42OM322AtAuqeJ4alI73AalS8Tvq3eD8rtlia10HqqxxNhbUnIY3fd">
                    <input type="submit" value="삭제" class="btn btn-danger">
                  </form>
                
              </div>
              <hr>
            </div>
`)
            commentform.reset()
          })
      })

    // 댓글 삭제12
    const commentDeleteForms = document.querySelectorAll('.comment-delete-forms')
    
    // 모든 댓글 삭제 form에 이벤트 등록
    commentDeleteForms.forEach(form => {
      form.addEventListener('submit', event => {
        event.preventDefault()
        const reviewId = event.target.dataset.reviewId
        const commentId = event.target.dataset.commentId

        axios({
          method: 'post',
          url: `/reviews/${reviewId}/comment/${commentId}/delete/`,
          headers: {'X-CSRFToken': csrf_token},
        })
        .then(response => {
          const comment = document.querySelector(`#comment-${commentId}`)
          const is_deleted = response.data.is_deleted
          const commentCount = document.querySelector('#comment-count')

          commentCount.innerText = response.data.commentCount

          if (is_deleted === true) {
            comment.remove()
          }
        })
      })
    })
  </script>
{% endblock script %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center">게시글</h1>

  <div class="">
    <a class="btn btn-primary float-end" href="{% url 'reviews:create' %}">
      글 작성</a>
  </div>

  <div class="container d-flex justify-content-center">
    <div class="row">
      {% for review in reviews %}

      <div class="col-sm-12 col-md-6 col-lg-3 d-flex justify-content-center">
          <div class="card m-3" style="width: 18rem; min-width: 10rem; ">
            {% if review.thumbnail %}
            <img src="{{ review.thumbnail.url }}" class="card-img-top " alt="dummy-img" height="300px">
            {% else %}
            <img src="https://dummyimage.com/600x400/000/fff" class="card-img-top " alt="dummy-img" height="300px">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title text-center"><a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a></h5>
              {% comment %} <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> {% endcomment %}
              <a href="{% url 'reviews:detail' review.pk %}" class="float-end btn btn-primary">자세히 보기</a>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
{% endblock content %}