accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.detail, name='detail'),
    path('<int:user_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/',include('reviews.urls')),
    path('accounts/', include('accounts.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
   class Meta(UserCreationForm.Meta): 
        model = get_user_model()
        fields = ('username', 'password1', 'password2')
        labels = {
            'username':'닉네임',
            'password1': '비밀번호',
            'password2' : '비밀번호 확인'
        }

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('email', 'last_name', 'first_name')
        labels = {
            'email' : '이메일',
            'last_name': '성',
            'first_name' : '이름'
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


# Create your views here.
def index(request):
    users = get_user_model().objects.all()

    print(users)

    context = {
        "users": users,
    }

    return render(request, "accounts/index.html", context)


def signup(request):
    if request.user.is_authenticated:
        return redirect("accounts:index")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("accounts:index")

    else:
        form = CustomUserCreationForm()

    context = {
        "form": form,
    }

    return render(request, "accounts/signup.html", context)


def login(request):
    if request.user.is_authenticated:
        return redirect("accounts:index")

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("accounts:index")

    else:
        form = AuthenticationForm()

    context = {
        "form": form,
    }

    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:index")


def detail(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)

    context = {
        "user": user,
    }

    return render(request, "accounts/detail.html", context)


@login_required
def update(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)

    if request.user != user:
        return redirect("accounts:detail", user_pk)

    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=user)

        if form.is_valid():
            form.save()
            return redirect("accounts:detail", user_pk)

    else:
        form = CustomUserChangeForm(instance=user)

    context = {
        "form": form,
    }

    return render(request, "accounts/update.html", context)


def follow(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)

    if user == request.user:
        return redirect("accounts:detail", user_pk)

    if user.followers.filter(pk=request.user.pk).exists():
        user.followers.remove(request.user)
        is_followed = False
    else:
        user.followers.add(request.user)
        is_followed = True

    context = {
        "followers_count": user.followers.count(),
        "followings_count": user.followings.count(),
        "is_followed": is_followed,
    }

    return JsonResponse(context)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <h1 class="text-center my-5">
    <span class="text-primary">{{ user.username }}</span>님의 페이지</h1>

  <!-- 프로필 이미지, 닉네임, 유저네임, 소개글 -->
  <div class="container d-grid p-3 rounded-4 border border-1 mb-5">
    <div class="row row-cols-2 align-items-center">
      <div class="col-3">
        <img src="{% static 'images/dummy-image-square.jpg' %}" alt="" class="rounded-4 border border-1 w-100">
      </div>

      <div class="col-9 p-3" style="height: 100%">
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <h3 class="m-0 me-3">{{ user.username }}</h3>
            <h5 class="m-0 text-muted">{{ user.last_name }}{{ user.first_name }}</h5>
          </div>
          <div>
            <!-- 로그인 유저 == 회원 정보 페이지의 유저 -->
            {% if request.user == user %}
              <a href="{% url 'accounts:update' user.pk %}" class="btn btn-primary">회원 정보 수정</a>
              <!-- 로그인 유저 -->
            {% elif request.user.is_authenticated %}
              <!-- 로그인 한 유저가 이미 팔로잉 중일 때 -->
              <form id="follow-form" data-user-id="{{ user.pk }}">
                {% csrf_token %}
                {% if request.user in user.followers.all %}
                  <input class='btn btn-danger' type="submit" value="언팔로우">
                {% else %}
                  <input class='btn btn-success' type="submit" value="팔로우">
                {% endif %}
                </form>
            {% endif %}

            

          </div>
        </div>
        <hr>

        <p class="text-muted m-0">
          <span  class="me-3">팔로잉
            <span id="followings-count">{{ user.followings.all|length }}</span>명</span>
          <span >팔로워
            <span id="followers-count">{{ user.followers.all|length }}</span>명</span>
        </p>
      </div>
    </div>
  </div>
{% endblock content %}

{% block script %}

  <script>
    const form = document.querySelector("#follow-form")
    const csrf_token = document.querySelector('[name=csrfmiddlewaretoken]').value
      form
      .addEventListener('submit', function (event) {
        event.preventDefault()
        const userId = event
          .target
          .dataset
          .userId

          axios({
            method: "post",
            url: `/accounts/${userId}/follow/`,
            headers: {
              'X-CSRFToken': csrf_token
            }
          })
          .then((response) => {
            const followersCount = response.data.followers_count
            const followingsCount = response.data.followings_count
            const isFollowed = response.data.is_followed
            const followBtn = document.querySelector('#follow-form > input[type=submit]')
            if (isFollowed === true) {
              followBtn.value = '언팔로우'
              followBtn.classList.add('btn-danger')
              followBtn.classList.remove('btn-success')
            } else {
              followBtn.value = '팔로우'
              followBtn.classList.add('btn-success')
              followBtn.classList.remove('btn-danger')
              
            }


            const followersCountTag = document.querySelector('#followers-count')
            const followingsCountTag = document.querySelector('#followings-count')
            followersCountTag.innerText = followersCount
            followingsCountTag.innerText = followingsCount
            
          })

      })
  </script>
{% endblock script %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center my-5">회원 목록</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr onclick="goToDetail('{{ user.pk }}')">
          <td>{{ user.id }}</td>
          <td>{{ user.username }}</td>
          <td>{{ user.email }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

{% block script %}
<script>
  function goToDetail(user_pk) {
    location.href = "{% url 'accounts:detail' 0 %}".replace('0', user_pk);
  }
</script>
{% endblock script %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center my-5">로그인</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}

    <div class="text-end">
      <a href="{% url 'accounts:signup' %}" class="btn btn-outline-primary">회원가입</a>
      <input type="submit" value="로그인" class="btn btn-primary">
    </div>
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center my-5">회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}

    <div class="text-end">
      <input type="submit" value="회원가입" class="btn btn-primary">
    </div>
  </form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center my-5">회원 정보 수정</h1>
  <form action="{% url 'accounts:update' request.user.pk %}" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}

    <div class="text-end">
      <input type="submit" value="수정하기" class="btn btn-primary">
    </div>
  </form>
{% endblock content %}