accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.detail, name='detail'),
    path('<int:user_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/',include('reviews.urls')),
    path('accounts/', include('accounts.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:review_pk>/comment/', views.comment_create,name='comment_create'),
    path('<int:review_pk>/comment/<int:comment_pk>/delete/', views.comment_delete,name='comment_delete'),
]

templates/base.html
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <!-- Icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
  <title>Document</title>
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'reviews:index' %}">LOGO</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            {% if request.resolver_match.app_name == 'reviews' and request.resolver_match.url_name == 'index' %}
              <a class="nav-link active" aria-current="page" href="{% url 'reviews:index' %}">Home</a>
            {% else %}
              <a class="nav-link" aria-current="page" href="{% url 'reviews:index' %}">Home</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if request.resolver_match.app_name == 'accounts' and request.resolver_match.url_name == 'index' %}
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:index' %}">Users</a>
            {% else %}
              <a class="nav-link" aria-current="page" href="{% url 'accounts:index' %}">Users</a>
            {% endif %}
          </li>
          
          <!-- 로그인 O -->
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              {% if request.resolver_match.app_name == 'accounts' and request.resolver_match.url_name == 'detail' and request.user == user %}
                <a class="nav-link active" href="{% url 'accounts:detail' request.user.pk %}">{{ request.user.username }}'s Page</a>
              {% else %}
                <a class="nav-link" href="{% url 'accounts:detail' request.user.pk %}">{{ request.user.username }}'s Page</a>
              {% endif %}
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          <!-- 로그인 X -->
          {% else %}
            <li class="nav-item">
              {% if request.resolver_match.url_name == 'login' %}
                <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
              {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              {% endif %}
            </li>
            
            <li class="nav-item">
              {% if request.resolver_match.url_name == 'signup' %}
                <a class="nav-link active" href="{% url 'accounts:signup' %}">Signup</a>
              {% else %}
                <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
              {% endif %}
            </li>
          {% endif %}
        </ul>
        
        <form class="d-flex" role="search" action="">
          <select class="form-select" aria-label="Default select example" name='Search_option'>
            <option value="movie_name__contains">영화제목</option>
            <option value="title__contains">리뷰제목</option>
            {% comment %} <option value="user__contains">작성자</option> {% endcomment %}
          </select>

          <input class="form-control mx-2" type="search" placeholder="Search" aria-label="Search" name='search'>
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <div class="container my-5">
    {% block content %}
    {% endblock content %}
  </div>

  <!-- JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <!-- Axios -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  {% block script %}
  {% endblock script %}
</body>
</html>